### ISSUE TITLE
Scylla not connectable after successful flash with default firmware

### ISSUE THREAD

**Issue by tim-hilt** [vattern/zmk-config#3]
I forked this repo and flashed the default firmware on my Scylla successfully. However, when I try to connect to the board afterwards, I get an error saying, that the setup has failed. This is consistent with my ThinkPad and iPhone.

I build my Scylla with nice!nanos v2.

Have you had this error before? Any idea how I could solve it?

**Comment by vattern** [comment]
This repo is not for nice!nanos, it is designed to go with hardware from https://github.com/vattern/holiot-carrier

**Comment by tim-hilt** [comment]
Thanks for the information! This helps tremendously. Do you know about a zmk/nice!nano/Scylla enabled config by any chance?
