### ISSUE TITLE
Question about enabling ZMK's RGB Underglow for per key RGB

### ISSUE THREAD

**Issue by webhostsg** [vattern/zmk-config#4]
Looking at ZMK's doc RGB Underglow could be used to under key RGB lighting.  I need to define the mosi-pin, sck-pin, and miso-pin. But I noticed that the Left and Right have different pins connected to the mosi-pin, sck-pin, and miso-pin. Do I take the pinouts from Left, since it's defined as ZMK_SPLIT_BLE_ROLE_CENTRAL?

**Comment by vattern** [comment]
you would need to do a define in the left and right `.dts` files. I have _not_ tested RGB as that's a battery hog.
